apiVersion: v2
name: dummy3tier-umbrella
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: dummy3tier-database
  version: "0.1.0"
  repository: "file://../database"
  condition: database.enabled
- name: dummy3tier-backend
  version: "0.1.0"
  repository: "file://../backend"
  condition: backend.enabled
- name: dummy3tier-frontend
  version: "0.1.0"
  repository: "file://../frontend"
  condition: frontend.enabled