{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.appname }}
spec:
  rules:
    - http:
        paths:
          - path: /
            {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
            pathType: Prefix
            defaultBackend:
              service:
                name: {{ .Values.appname }}
                port:
                  number: 3000
            {{ else -}}
            backend:
              serviceName: {{ .Values.appname }}
              servicePort: 3000
            {{ end }}
