appname: dummy3tier-frontend
image: 
  name: frontend
  tag: latest
  pullpolicy: IfNotPresent
database:
  secretname: dummy3tier-frontend
replicas: 1
middleware:
  service:
    name: dummy3tier-backend
    port: "8000"
