apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app:  {{ .Values.appname }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
    spec:
      containers:
        - name: application
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullpolicy }}
          env:
            - name: ADDRESS
              value: 0.0.0.0:8000
            - name: RUST_LOG
              value: info
            - name: PG_DBNAME
              value: {{ .Values.database.name }}
            - name: PG_HOST
              value: {{ .Values.database.uri }}
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretname }}
                  key: user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretname }}
                  key: password
          ports:
            - containerPort: 80
              name: http

