appname: dummy3tier-backend
image: 
  name: backend
  tag: latest
  pullpolicy: IfNotPresent
database:
  service:
    name: dummy3tier-database
  name: postgres
  secretname: dummy3tier-backend
replicas: 1
appdebug:
  level: info
  backtrace: 0
